### ISSUE TITLE
platexrelease で Missing \begin{document}

### ISSUE THREAD

**Issue by aminophen** [zr-tex8r/PXjahyper#3]
@zr-tex8r

pxjahyper.sty 2020/09/27 v0.5a において，platexrelease で巻き戻すと

``` tex
\listfiles
\RequirePackage[2020/02/02]{platexrelease}
\documentclass[dvipdfmx]{article}
\usepackage{hyperref}
\usepackage{pxjahyper}
\begin{document}
ここから\hfill ここまで
\end{document}
```

```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.315 ...\pxhy@out@special{pdf:tounicode EUC-UCS2}
```

のエラーが出ます。

**Comment by zr-tex8r** [comment]
```tex
\RequirePackage[2020/02/02]{latexrelease}
\show\AddToHook%==> \AddToHook=\long macro:#1#2->.
```

なんだこりゃ？🤔

**Comment by aminophen** [comment]
えーっ😨（pLaTeX の判定コードも書き直さないとまずいですね…）

**Comment by aminophen** [comment]
いやでも \AddToHook が `\@gobbletwo` になっているとすると引数の数が違う（オプション引数が捨てられない）ので，これは LaTeX2e 側の問題というべきでしょうか？

**Comment by aminophen** [comment]
https://github.com/latex3/latex2e/issues/401

**Comment by zr-tex8r** [comment]
lthooks-code を見る限りは、lthooks関係のrollbackは全部「何もしないやつ」で再定義しているなあ。
（理由についてはまだ理解していない。）

```tex
\IncludeInRelease{0000/00/00}%
                 {\NewHook}{The hook management}%

\def \NewHook#1{}
\def \NewReversedHook#1{}
\def \NewMirroredHookPair#1#2{}

\long\def \AddToHook#1#2{}

\def \AddToHookNext#1{\@gobble@AddToHook@args}
\providecommand\@gobble@AddToHook@args[2][]{}

\def\RemoveFromHook#1{\@gobble@RemoveFromHook@arg}
\providecommand\@gobble@RemoveFromHook@arg[1][]{}

\def \UseHook        #1{}
\def \UseOneTimeHook #1{}
\def \ShowHook #1{}
\let \DebugHooksOn \@empty
\let \DebugHooksOff\@empty

\def \DeclareHookRul#1#2#3#4{}
\def \DeclareDefaultHookRule #1#2#3{}
\def \ClearHookRule#1#2#3{}
\def \IfHookExistTF #1#2#3{#3}
\def \IfHookEmptyTF #1#2#3{#2}

\EndIncludeInRelease
```

> 引数の数が違う

たぶん、`\AddToHook` と `\AddToHookNext`（←オプション引数なし）の再定義が逆になってると思う。

あとそれから、`\IfHookExistTF`  `\IfHookEmptyTF` の再定義の `\long` が抜けてる。

**Comment by aminophen** [comment]
ありがとうございます。理由については

> Rolling back here doesn’t undefine the interface commands
> as they may be used in packages without rollback functionality.

とのことで，逆に rollback を考慮しているパッケージが動かないのですね…。

> 再定義が逆，再定義の `\long` が抜けてる

調査ありがとうございます。確かに…。

**Comment by zr-tex8r** [comment]
で、それらは多分LaTeXカーネル側の（小さな？）問題なんだけど、いずれにしても、「rollbackした状態だと旧カーネル用のコードを実行する必要がある」というのは変わらないはず……。

どうしようかな……🤔

**Comment by zr-tex8r** [comment]
> 理由については

「何もしないやつ」に変えている以上、「rollbackを考慮していないやつ」は結局意図通りに動くはずがないわけで、やっぱり謎🤔なんですよね……。

**Comment by aminophen** [comment]
> 「何もしないやつ」に変えている以上、「rollbackを考慮していないやつ」は結局意図通りに動くはずがないわけで、やっぱり謎

それはそうですね…。

「フック機能が利用できるかどうか」を「`\AddToHook` が定義済みかどうか」で判定不能となると，何を持って判定するのが良いのでしょうか？ pLaTeX にも同様の判定を仕込んでいたのですが，唯一確実そうな「\fmtversion を判定」は筋が悪いのであまり使いたくないので困りました。

**Comment by zr-tex8r** [comment]
> 「フック機能が利用できるかどうか」を「\AddToHook が定義済みかどうか」で判定不能となると，何を持って判定するのが良いのでしょうか？ pLaTeX にも同様の判定を仕込んでいたのですが，唯一確実そうな「\fmtversion を判定」は筋が悪いのであまり使いたくないので困りました。

なにも思いつかない（ざんねん🙃）

**Comment by zr-tex8r** [comment]
あつ！ etoolboxも `\ifdef\AddToHook` をやってる！🙃

**Comment by aminophen** [comment]
聞いてみよう🙃 https://github.com/latex3/latex2e/issues/401#issuecomment-703207370

**Comment by aminophen** [comment]
うーん🤔 https://github.com/latex3/latex2e/issues/401#issuecomment-703246198

**Comment by zr-tex8r** [comment]
うーむ、ということは、これは「特殊ケース」だから`\fmtversion`で判定するのが妥当、ということになるのかな😑

**Comment by zr-tex8r** [comment]
v0.6 をリリース。

* tounicode special出力のコードがあちこちに散在していると改修が面倒なことになるので、「special出力」の部分だけ別パッケージ（pxjahyper-enc）に切り出した。BXjsclsはこのpxjahyper-encを読むように改修するつもり。

**Comment by aminophen** [comment]
ありがとうございます。
